[package]
name = "sgx-scroll-verifier"
version.workspace = true
edition.workspace = true

[features]
tstd_app = ["automata-sgx-sdk/tstd_app"]

[package.metadata.sgx]
app_scroll_verifier = { path = "../../crates/app-scroll-verifier", config = "sgx/config.xml", edl = "sgx/enclave.edl", lds = "sgx/enclave.lds", key = "sgx/private.pem", env = ["PKG_CONFIG_ALLOW_CROSS=1"] }

[dependencies]
serde.workspace = true
serde_json.workspace = true
automata-sgx-sdk.workspace = true

[build-dependencies]
automata-build-script.workspace = true